/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Список будущих бронирований (startUtc > now), отсортирован по startUtc asc.
         *     Без пагинации (MVP). Брони всех типов событий в одном массиве.
         */
        get: operations["BookingsManagement_listUpcomingBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список всех типов события (управленческий, включая все активные). */
        get: operations["EventTypeManagement_listEventTypes"];
        put?: never;
        /** @description Создать тип события. id-slug задаёт владелец, должен быть уникальным. */
        post: operations["EventTypeManagement_createEventType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить один тип события по slug. */
        get: operations["EventTypeManagement_getEventType"];
        /** @description Обновить название/описание/длительность. id не меняется. */
        put: operations["EventTypeManagement_updateEventType"];
        post?: never;
        /** @description Удалить тип события. Запрещено (409), если по типу есть бронирования. */
        delete: operations["EventTypeManagement_deleteEventType"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить текущий профиль владельца. */
        get: operations["OwnerManagement_getOwner"];
        /** @description Задать/обновить профиль владельца (имя + email). */
        put: operations["OwnerManagement_updateOwner"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список доступных длительностей события (15 и 30 минут). */
        get: operations["Public_listEventTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Описание одного типа события по ссылке-приглашению вида /booking/{id}. */
        get: operations["Public_getEventType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/event-types/{id}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Свободные слоты на 14 дней вперёд от сегодня (UTC), сетка 15 минут. */
        get: operations["Public_listAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/event-types/{id}/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Создать бронирование выбранным слотом. Идемпотентность по Idempotency-Key.
         *     201 Booking | 409 если слот занят | 404 если eventTypeId/слот не найдены.
         */
        post: operations["Public_createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Созданное гостем бронирование. */
        Booking: {
            /**
             * Format: uuid
             * @description Идентификатор брони.
             */
            id: string;
            /** @description Идентификатор забронированного слота. */
            slotId: components["schemas"]["SlotId"];
            /** @description Тип события, по которому создана бронь. */
            eventType: components["schemas"]["EventType"];
            /**
             * Format: date-time
             * @description Начало встречи в UTC (дублирует данные слота для удобства фронта).
             */
            startUtc: string;
            /**
             * Format: date-time
             * @description Конец встречи в UTC.
             */
            endUtc: string;
            /** @description Данные гостя. */
            guest: components["schemas"]["Guest"];
            /**
             * Format: date-time
             * @description Время создания брони в UTC.
             */
            createdAt: string;
        };
        /** @description Тело запроса на создание бронирования. */
        BookingRequest: {
            /** @description Идентификатор слота, который гость хочет забронировать. */
            slotId: components["schemas"]["SlotId"];
            /** @description Данные гостя. */
            guest: components["schemas"]["Guest"];
        };
        /** @description Тело запроса на создание типа события. id задаёт владелец, далее не меняется. */
        CreateEventTypeRequest: {
            /** @description Slug типа события, уникальный. */
            id: components["schemas"]["EventTypeId"];
            /** @description Название. */
            name: string;
            /** @description Описание. */
            description: string;
            /** @description Длительность в минутах (5..480). */
            durationMinutes: components["schemas"]["DurationMinutes"];
        };
        /**
         * Format: int16
         * @description Доступные длительности события (минуты). Произвольное значение 5..480.
         */
        DurationMinutes: number;
        /** @description Ответ с ошибкой (упрощённый набор для MVP). */
        ErrorResponse: {
            /**
             * Format: int16
             * @description HTTP-статус.
             */
            status: number;
            /** @description Краткое сообщение об ошибке. */
            message: string;
        };
        /** @description Тип события, создаваемый владельцем. Длительность произвольная 5..480 минут. */
        EventType: {
            /** @description Идентификатор-slug, задаваемый владельцем (например, "intro-call"). */
            id: components["schemas"]["EventTypeId"];
            /** @description Название типа события, отображается гостям. */
            name: string;
            /** @description Описание типа события (текст для гостей). */
            description: string;
            /** @description Длительность в минутах (5..480). */
            durationMinutes: components["schemas"]["DurationMinutes"];
        };
        /** @description Идентификатор типа события — slug, задаваемый владельцем (например, "intro-call"). */
        EventTypeId: string;
        /** @description Гость — тот, кто бронирует слот. Без аккаунта. */
        Guest: {
            /** @description Имя гостя. */
            name: string;
            /** @description Email гостя для связи. */
            email: string;
        };
        /** @description Единственный владелец календаря. Профиль задан заранее, без регистрации. */
        Owner: {
            /** @description Фиксированный идентификатор владельца. */
            id: string;
            /** @description Имя владельца, отображается гостям. */
            name: string;
            /** @description Email владельца, куда приходят брони (в админке задаётся один раз). */
            email: string;
        };
        /** @description Кандидат на бронь, генерируется сервером на 14 дней вперёд, сетка 15 мин, UTC. */
        Slot: {
            /** @description Идентификатор слота, UTC-слаг YYYYMMDDTHHMM. */
            id: components["schemas"]["SlotId"];
            /**
             * Format: date-time
             * @description Начало слота в UTC.
             */
            startUtc: string;
            /**
             * Format: date-time
             * @description Конец слота в UTC = startUtc + durationMinutes.
             */
            endUtc: string;
            /** @description Длительность слота в минутах (берётся из типа события). */
            durationMinutes: components["schemas"]["DurationMinutes"];
            /** @description Текущая доступность слота. */
            status: components["schemas"]["SlotStatus"];
        };
        /** @description Идентификатор слота — UTC-слаг формата YYYYMMDDTHHMM (например, 20260811T0930). */
        SlotId: string;
        /**
         * @description Статус слота для бронирования.
         * @enum {string}
         */
        SlotStatus: "available" | "booked";
        /** @description Тело запроса на обновление типа события. id не меняется (в path). */
        UpdateEventTypeRequest: {
            /** @description Название. */
            name: string;
            /** @description Описание. */
            description: string;
            /** @description Длительность в минутах (5..480). */
            durationMinutes: components["schemas"]["DurationMinutes"];
        };
        /** @description Тело запроса на обновление профиля владельца. */
        UpdateOwnerRequest: {
            name: string;
            email: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    BookingsManagement_listUpcomingBookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
        };
    };
    EventTypeManagement_listEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    EventTypeManagement_createEventType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventTypeRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"] | components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    EventTypeManagement_getEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["EventTypeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"] | components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    EventTypeManagement_updateEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["EventTypeId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventTypeRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"] | components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    EventTypeManagement_deleteEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["EventTypeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OwnerManagement_getOwner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Owner"] | components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    OwnerManagement_updateOwner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOwnerRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Owner"] | components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Public_listEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    Public_getEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["EventTypeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"] | components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Public_listAvailability: {
        parameters: {
            query?: {
                fromUtc?: string;
                toUtc?: string;
            };
            header?: never;
            path: {
                id: components["schemas"]["EventTypeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slot"][] | components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Public_createBooking: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                id: components["schemas"]["EventTypeId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"] | components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
